In [ ]:
import numpy as np

In [ ]:
# las condiciones se usan cuando los slices no son suficientes para manipular datos más especificos
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
indices_cond = arr > 5 # retorna una lista booleana
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[indices_cond] # retorna los valores en True

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[(arr > 5)] = 99 # cambia el valor de los que cumplen la condición
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [ ]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

In [ ]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
print(arr[arr % 2 == 0]) # pares
print(arr[arr % 2 == 1]) # inpares
print(arr[arr % 3 == 0]) # multiplos de 3

[ 2  4  6  8 10]
[1 3 5 7 9]
[3 6 9]


In [ ]:
matriz = np.random.randint(2, 99, (3, 3))
matriz

array([[13, 27, 31],
       [64, 84,  7],
       [67, 77, 40]])

In [ ]:
matriz_filtrada = np.where(matriz > 50, True, False)
matriz_filtrada

array([[False, False, False],
       [ True,  True, False],
       [ True,  True, False]])

In [ ]:
tensor = np.random.randint(0, 20, (3, 3, 2))
tensor

array([[[13, 10],
        [ 7,  4],
        [19,  7]],

       [[14, 16],
        [ 1, 12],
        [ 9,  7]],

       [[14,  3],
        [10, 15],
        [15,  6]]])

In [ ]:
pares = tensor[tensor % 2 == 0]
pares

array([10,  4, 14, 16, 12, 14, 10,  6])

In [ ]:
impares = tensor[tensor % 2 == 1]
impares

array([13,  7, 19,  7,  1,  9,  7,  3, 15, 15])

In [ ]:
cifras_2 = tensor[tensor // 10 > 0]
cifras_2

array([13, 10, 19, 14, 16, 12, 14, 10, 15, 15])

In [ ]:
cifras_1 = tensor[tensor // 10 == 0]
cifras_1

array([7, 4, 7, 1, 9, 7, 3, 6])

In [ ]:
divisores_tres_y_cuatro = tensor[(tensor % 3 == 0) & (tensor % 4 == 0)]
divisores_tres_y_cuatro

array([12])

In [ ]:
# potencia al cuadrado y raíz par
p_r_p = tensor[((tensor ** 2) % 2 == 0) & ((tensor**(1/2)) % 2 == 0)]
p_r_p

array([ 4, 16])

In [ ]:
divisores_tres_o_cuatro = tensor[(tensor % 3 == 0) | (tensor % 4 == 0)]
divisores_tres_o_cuatro.sort()
divisores_tres_o_cuatro

array([ 3,  4,  6,  9, 12, 15, 15, 16])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4950ccd9-74b8-4ba2-b588-82894596c11f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>