In [2]:
import numpy as np

In [ ]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# arange(start, ends, steps)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# zeros(shape)
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10, 5, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]

In [5]:
#  linspace(star, end, cantidad)
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [6]:
# matriz identidad
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# valor aleatorio
np.random.rand()

0.5221742583960903

In [8]:
np.random.rand(4)

array([0.90483741, 0.32046062, 0.17815617, 0.58263336])

In [10]:
np.random.rand(4, 4)

array([[0.8470223 , 0.02009702, 0.28513106, 0.41669555],
       [0.81705147, 0.20936593, 0.15849093, 0.60469001],
       [0.54044542, 0.89145041, 0.12714481, 0.27914585],
       [0.93302605, 0.17863895, 0.8507033 , 0.83751468]])

In [11]:
# .randint(star, end, dimesiones)
np.random.randint(1, 100, (10, 10))

array([[33,  6,  6, 32, 96, 62, 26, 27, 66, 52],
       [21,  2, 60, 60, 58, 81, 27, 89, 48, 78],
       [51, 89, 12, 87, 34, 62, 21, 69,  5, 93],
       [10, 34, 13, 10, 84, 95, 77, 92, 38, 77],
       [46, 16, 52, 30, 37, 98, 88, 12,  5, 42],
       [83, 26, 46, 91, 76,  2,  5, 27,  3, 81],
       [43, 78,  1, 93, 22, 31, 33, 11, 88, 63],
       [19,  8, 55, 32, 51, 61, 55, 76, 69, 37],
       [89, 13, 69, 22, 14,  7, 10,  8, 95, 77],
       [59, 84, 57, 54, 47, 24, 24, 50, 26, 44]])

In [15]:
print(np.random.poisson.__doc__)


        poisson(lam=1.0, size=None)

        Draw samples from a Poisson distribution.

        The Poisson distribution is the limit of the binomial distribution
        for large N.

        .. note::
            New code should use the ``poisson`` method of a ``default_rng()``
            instance instead; please see the :ref:`random-quick-start`.

        Parameters
        ----------
        lam : float or array_like of floats
            Expected number of events occurring in a fixed-time interval,
            must be >= 0. A sequence must be broadcastable over the requested
            size.
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
            ``m * n * k`` samples are drawn.  If size is ``None`` (default),
            a single value is returned if ``lam`` is a scalar. Otherwise,
            ``np.array(lam).size`` samples are drawn.

        Returns
        -------
        out : ndarray or scalar
 

In [21]:
np.random.poisson(5, 200)

array([ 5,  3,  6,  3,  4,  7,  4,  4,  3,  3,  7,  7,  4,  6,  8,  3,  5,
        7,  8,  7, 10,  5,  4,  2,  7,  6,  4,  5,  5,  6,  6,  6,  3,  5,
        3,  7,  9,  4,  4,  9,  4,  5,  2,  6,  5,  1, 14,  5,  4,  4,  7,
        3,  3,  6,  6,  6,  4,  3,  7,  1,  5,  3,  5,  6,  6,  3,  5,  3,
        3, 11,  6,  6,  5,  4,  5,  5,  7,  4,  2,  3,  3,  5,  5,  5,  6,
        4,  1,  5,  6,  5,  5,  7,  5, 12,  5,  5,  2,  2,  2,  6,  5,  4,
        4,  7,  4,  6,  7,  7,  3,  5,  4,  3,  6,  5,  5,  5,  5,  6,  2,
        5,  8,  7,  5,  3,  5,  7,  4,  2,  2,  3,  4,  4,  6,  2,  5,  6,
        3,  6,  4,  4,  3,  8,  6,  6,  4,  5,  3,  8,  4,  3,  7,  4,  6,
       10,  5,  6,  5,  3,  5,  4,  5,  3,  3,  7,  3,  4, 12, 10,  3,  4,
        7,  6,  6, 10,  7,  2,  6,  5,  7,  3,  7,  6, 10,  3,  9,  6,  8,
        5, 10,  4,  4,  5,  6,  7,  7,  5,  3, 11,  4,  7])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4950ccd9-74b8-4ba2-b588-82894596c11f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>