In [ ]:
import numpy as np

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 2, 24]], [[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 2, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 24]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 24]]]


3

### Agregar o eliminar dimensiones

In [ ]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector, vector.ndim)

vector_2 = np.squeeze(vector)

print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Reto
1. Crear un tensor de 5 dimensiones.
2. Sumar una dimensión en algún eje.
3. Borrar dimensiones que no se usen.

In [ ]:
# array de 5 dimensione
#tensor_cinco = np.array([[[[1, 2],[3, 4]], [[5, 6],[7, 8]]], [[[1, 2],[3, 4]], [[5, 6],[7, 8]]]], ndmin = 5)
tensor_cinco = np.array([[[1,3, 4, 5]]], ndmin = 5)
print(tensor_cinco)
tensor_cinco.ndim

[[[[[1 3 4 5]]]]]


5

In [ ]:
tensor_cinco.squeeze()
tensor_cinco, tensor_cinco.ndim

(array([[[[[1, 3, 4, 5]]]]]), 5)

In [ ]:
tensor_cinco = tensor_cinco.squeeze()
tensor_cinco, tensor_cinco.ndim

(array([1, 3, 4, 5]), 1)

In [ ]:
expand_cinco = np.expand_dims(tensor_cinco, axis=1)
print(expand_cinco)
expand_cinco.ndim

[[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]


   [[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]]


6

In [ ]:
print(expand_cinco, expand_cinco.ndim, '\n', '*'*10, '\n', tensor_cinco, tensor_cinco.ndim)
clean = expand_cinco.squeeze()
clean_dos = tensor_cinco.squeeze()
print('*' * 10)
print(clean, clean.ndim, '\n', '*'*10, '\n', clean_dos, clean_dos.ndim)

[[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]


   [[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]] 6 
 ********** 
 [[[[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]


  [[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]]] 5
**********
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]] 4 
 ********** 
 [[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]] 4


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4950ccd9-74b8-4ba2-b588-82894596c11f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>