In [ ]:
import numpy as np

In [ ]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# Declarar un array de dos dimensiones
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Acceder a los elementos mediante index
# Se inicia desde cero

arr[1]

7

In [ ]:
arr[0] + arr[5]

7

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[0, 2]

3

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:6] # slices, no toma en cuenta el limite

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[::3]

array([1, 4, 7])

In [ ]:
arr[-3::]

array([7, 8, 9])

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# matriz[filas, columnas] 
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
m3D=np.array([[[5,4,4],[6,1,9],[7,8,2]], [[4,7,1],[8,3,0],[0,0,1]], [[6,0,1],[4,3,6],[9,9,1]]])
m3D

array([[[5, 4, 4],
        [6, 1, 9],
        [7, 8, 2]],

       [[4, 7, 1],
        [8, 3, 0],
        [0, 0, 1]],

       [[6, 0, 1],
        [4, 3, 6],
        [9, 9, 1]]])

In [ ]:
matriz = np.random.randint(90, 100, size = (3, 3, 3))
matriz

array([[[91, 92, 90],
        [99, 93, 97],
        [99, 94, 92]],

       [[94, 92, 91],
        [96, 90, 90],
        [99, 95, 99]],

       [[94, 90, 90],
        [99, 90, 98],
        [92, 92, 94]]])

In [ ]:
print(np.random.randint.__doc__)


        randint(low, high=None, size=None, dtype=int)

        Return random integers from `low` (inclusive) to `high` (exclusive).

        Return random integers from the "discrete uniform" distribution of
        the specified dtype in the "half-open" interval [`low`, `high`). If
        `high` is None (the default), then results are from [0, `low`).

        .. note::
            New code should use the ``integers`` method of a ``default_rng()``
            instance instead; please see the :ref:`random-quick-start`.

        Parameters
        ----------
        low : int or array-like of ints
            Lowest (signed) integers to be drawn from the distribution (unless
            ``high=None``, in which case this parameter is one above the
            *highest* such integer).
        high : int or array-like of ints, optional
            If provided, one above the largest (signed) integer to be drawn
            from the distribution (see above for behavior if ``high=None``).
 

In [ ]:
matriz[0, 2, 1]

90

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4950ccd9-74b8-4ba2-b588-82894596c11f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>