In [1]:
import numpy as np

In [11]:
arr = np.random.randint(1, 20, 10)
arr

array([15, 17,  6,  7,  6, 13,  6, 16,  9,  3])

In [12]:
matriz = arr.reshape(2, 5)
matriz

array([[15, 17,  6,  7,  6],
       [13,  6, 16,  9,  3]])

In [13]:
arr.max() # el número más grande del array

17

In [14]:
matriz.max(1) # en el eje 1, o por fila

array([17, 16])

In [15]:
matriz.max(0) # en el eje 0, o por columna

array([15, 17, 16,  9,  6])

In [16]:
arr.argmax() # indice donde se encuentra el valor mayor

1

In [17]:
matriz.argmax(0) # indice del valor mayor por columnas

array([0, 0, 1, 1, 0])

In [18]:
matriz.argmax(1) # indice del valor mayor por filas

array([1, 2])

## Valor minimo

In [19]:
arr.min()

3

In [20]:
matriz.min(0)

array([13,  6,  6,  7,  3])

In [21]:
arr.argmin()

9

In [22]:
matriz.argmin(0)

array([1, 1, 0, 0, 1])

In [23]:
matriz.argmin(1)

array([2, 4])

In [25]:
arr

array([15, 17,  6,  7,  6, 13,  6, 16,  9,  3])

In [24]:
arr.ptp() # pick to pick, la diferencia entre el número mayor y el numero menor

14

In [33]:
matriz.ptp(0) # distacia entre los valores

array([ 2, 11, 10,  2,  3])

In [34]:
arr.sort()
arr

array([ 3,  6,  6,  6,  7,  9, 13, 15, 16, 17])

In [36]:
np.percentile(arr, 50)

8.0

In [38]:
np.median(arr)

8.0

In [40]:
np.median(matriz, 1)

array([ 6., 15.])

In [41]:
np.std(arr) #desviación estandar

4.749736834815167

In [44]:
np.std(matriz, 1)

array([1.356466  , 2.82842712])

In [47]:
np.var(arr), np.std(arr) ** 2 # la std al cuadrado es igual a la varianza

(22.560000000000002, 22.56)

In [49]:
print(np.mean(arr)) # la media es la suma de los valores divido en el tamaño del array
print(np.median(arr)) # percentil 50 

9.8
8.0


In [59]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
a, b

(array([[1, 2],
        [3, 4]]),
 array([5, 6]))

In [60]:
np.concatenate((a, b), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [61]:
a.ndim, b.ndim

(2, 1)

In [62]:
b = np.expand_dims(b, axis=0)

In [65]:
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
np.concatenate((a, b), axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [67]:
# uso de la transpuesta de una matriz con T
np.concatenate((a, b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4950ccd9-74b8-4ba2-b588-82894596c11f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>