In [3]:
import numpy as np

In [5]:
arr = np.random.randint(1, 10, (3, 2))
arr.shape # indica la forma del arreglo

(3, 2)

In [7]:
arr

array([[5, 6],
       [3, 7],
       [8, 3]])

In [6]:
arr.reshape(1, 6) # organiza el array de una forma distinta

array([[5, 6, 3, 7, 8, 3]])

In [8]:
arr.reshape(2, 3)

array([[5, 6, 3],
       [7, 8, 3]])

In [9]:
np.reshape(arr, (1, 6))

array([[5, 6, 3, 7, 8, 3]])

In [10]:
arr

array([[5, 6],
       [3, 7],
       [8, 3]])

In [11]:
# para lenguaje C
np.reshape(arr, (2, 3), 'C')

array([[5, 6, 3],
       [7, 8, 3]])

In [12]:
# para lenguaje Fortran
np.reshape(arr, (2, 3), 'F')

array([[5, 8, 7],
       [3, 6, 3]])

In [13]:
# como mejor este optimizado el almacenamiento en el sistema
np.reshape(arr, (2, 3), 'A')

array([[5, 6, 3],
       [7, 8, 3]])

## Reto
1. Crear un tensor de cualquier dimensión.
2. Jugar con los valores, haciendo reshape
3. Probar con valores fuera del rango

In [18]:
matriz_tred_dim = np.random.randint(1, 2, (3, 2, 4))
matriz_tred_dim

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
matriz_tred_dim.shape

(3, 2, 4)

In [23]:
matriz_tred_dim.reshape(24, 1, 1)
matriz_tred_dim.reshape(2, 3, 4)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [26]:
matriz_tred_dim.reshape(4, 6)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [29]:
matriz_tred_dim.reshape(1, 24)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1]])

In [33]:
matriz_tred_dim.reshape(6, 1, 4)

array([[[1, 1, 1, 1]],

       [[1, 1, 1, 1]],

       [[1, 1, 1, 1]],

       [[1, 1, 1, 1]],

       [[1, 1, 1, 1]],

       [[1, 1, 1, 1]]])

In [42]:
matriz_tred_dim.reshape(6, -1) # -1 se usa para que calcule numpy el valor faltante

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [43]:
matriz_tred_dim.reshape(6, 1, -1)

array([[[1, 1, 1, 1]],

       [[1, 1, 1, 1]],

       [[1, 1, 1, 1]],

       [[1, 1, 1, 1]],

       [[1, 1, 1, 1]],

       [[1, 1, 1, 1]]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4950ccd9-74b8-4ba2-b588-82894596c11f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>