In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1, 5)
arr.dtype

dtype('int64')

In [ ]:
arr = np.arange(1, 5, dtype='float64')
arr.dtype

dtype('float64')

In [ ]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [ ]:
arr = np.arange(0, 5)

arr = arr.astype(np.bool8)
arr

array([False,  True,  True,  True,  True])

In [ ]:
arr = np.arange(0, 5)

arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [ ]:
# Un único tipo de dato
arr = np.array(['0', '1', '2', '3', '4'])

arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [ ]:
print(np.arange.__doc__)

arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`. See the warnings section below for more information.

    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
    step : integer or real, optional
        Spacing b

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4950ccd9-74b8-4ba2-b588-82894596c11f' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>